parameters:
#    itarato_blog.example.class: Itarato\BlogBundle\Example

services:
#    itarato_blog.example:
#        class: %itarato_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
